// =====================================================================
// SHARED INGEST PIPELINE
// =====================================================================
// One function both ingest paths use:
//   - /api/process  (browser upload -> JSON files, local dev)
//   - /api/ingest   (API key push -> Postgres, production)
//
// Takes RAW parsed rows (from CSV or XLSX) and runs the full pipeline:
//   normalize headers -> strip RULI -> batch validate -> per-row validate
//   -> CSPRNG code + salt + hash -> split sensitive -> build records
//
// Returns plain data (no fs, no db) so the caller decides where it lands.
// =====================================================================

import crypto from "crypto";
import { normalizeHeaders } from "@/lib/headerAliases";
import { normalizeValues } from "@/lib/valueAliases";
import { normalizeDates } from "@/lib/dateNormalize";
import { rulesByEntity } from "@/lib/validationRules";
import { validateRecord, validateBatch } from "@/lib/validation";
import { generateCode, generateSalt, hashCode } from "@/lib/ruli";
import { buildMetadata, buildTables, buildRecord } from "@/lib/transform";
import { splitSensitive, sensitiveFields } from "@/lib/sensitiveFields";

const ENTITIES = ["staff", "institution"];

// Drop any RULI-ish column from an uploaded row. RULI is generated by the
// app (crypto), so an incoming value would be meaningless/unsafe to trust.
function stripRuli(rec) {
  const out = {};
  for (const [k, v] of Object.entries(rec)) {
    if (k.toLowerCase().replace(/[^a-z0-9]/g, "") === "ruli") continue;
    out[k] = v;
  }
  return out;
}

// Keep ONLY canonical (known) fields. Unknown columns are warned about by
// normalizeHeaders and must be genuinely dropped here -- otherwise an
// arbitrary uploaded column (e.g. "Email", "Notes") rides into the shareable
// dash record via splitSensitive (which treats every non-PII field as safe).
// "ignored" must mean ignored, not leaked.
function keepCanonical(rec, entity) {
  const allowed = new Set(Object.keys(rulesByEntity[entity] || {}));
  const out = {};
  for (const [k, v] of Object.entries(rec)) {
    if (allowed.has(k)) out[k] = v;
  }
  return out;
}

// Stable identity fingerprint for idempotent re-uploads. Built from the
// SENSITIVE (identifying) fields only, canonicalized so cosmetic differences
// (case, whitespace) don't defeat dedup. Combined with school_id at the DB
// layer to form the per-school uniqueness key.
function identityHash(data, entity) {
  const fields = (sensitiveFields[entity] || []).slice().sort();
  const parts = fields.map((f) => String(data[f] ?? "").trim().toLowerCase());
  return crypto.createHash("sha256").update(parts.join("")).digest("hex");
}

// processRows(rawRows, entity, { createdAt })
//   rawRows  : array of header-keyed objects (from parseUpload / parseCSV)
//   returns  : {
//     entity, total,
//     accepted: [{ record, mapping, identityHash }],   // record -> dash, mapping -> link table
//     rejected: [{ row, errors, data }],
//     headerAliasesApplied, valueAliasesApplied, dateNormalizationApplied, headerWarnings,
//     batchError: null | { error, errors }             // whole-batch failure
//   }
export function processRows(rawRows, entity, { createdAt, extraAliases = [] } = {}) {
  if (!ENTITIES.includes(entity)) {
    return { batchError: { error: `entity must be one of ${ENTITIES.join(", ")}` } };
  }
  if (!Array.isArray(rawRows) || rawRows.length === 0) {
    return { batchError: { error: "no rows: file empty or unparseable" } };
  }

  // ---- normalize header aliases (sex -> gender, dob -> date_of_birth, ...) ----
  const norm = normalizeHeaders(rawRows, entity);

  // ---- normalize enum VALUES (boy/m -> M, ...) -- extraAliases are the
  //      admin-approved value_aliases rows merged on top of the static set ----
  const vals = normalizeValues(norm.records, entity, rulesByEntity[entity], extraAliases);

  // ---- normalize DATES (15/03/2014, 15-Mar-2014, ... -> 2014-03-15) ----
  const dts = normalizeDates(vals.records, entity, rulesByEntity[entity]);
  const rows = dts.records.map(stripRuli).map((r) => keepCanonical(r, entity));

  const headerWarnings = [];
  if (norm.unknown.length) headerWarnings.push(`unrecognized columns ignored: ${norm.unknown.join(", ")}`);
  for (const c of norm.collisions) {
    headerWarnings.push(`columns [${c.from.join(", ")}] all map to "${c.canonical}" -- using last`);
  }
  // Dedupe unrecognized enum values for a compact warning (don't spam per-row).
  const unrecSeen = new Set();
  for (const u of vals.unrecognized) {
    const k = `${u.field}=${u.value}`;
    if (unrecSeen.has(k)) continue;
    unrecSeen.add(k);
    headerWarnings.push(`unrecognized ${u.field} value "${u.value}" -- left as-is (will fail validation if not allowed)`);
  }
  // Date format: note the file-level day/month-first decision + any unparsed.
  if (dts.applied.length && !dts.ambiguous) {
    headerWarnings.push(`dates read as ${dts.dayFirst ? "day/month/year" : "month/day/year"} and reformatted to ISO (YYYY-MM-DD)`);
  }
  if (dts.ambiguous && dts.applied.length) {
    headerWarnings.push(`ambiguous date order -- assumed ${dts.dayFirst ? "day/month/year" : "month/day/year"}; verify if your school uses the other order`);
  }
  const dateUnparsedSeen = new Set();
  for (const u of dts.unparsed) {
    const k = `${u.field}=${u.value}`;
    if (dateUnparsedSeen.has(k)) continue;
    dateUnparsedSeen.add(k);
    headerWarnings.push(`unrecognized ${u.field} date "${u.value}" -- left as-is (will fail validation)`);
  }

  // ---- batch-level validation ----
  const batch = validateBatch(rows, entity);
  if (!batch.valid) {
    return { batchError: { error: "batch validation failed", errors: batch.errors } };
  }

  const when = createdAt || new Date().toISOString();
  const accepted = [];
  const rejected = [];
  // Enum values that were rejected -> candidates for an admin to approve as a
  // new value alias. Deduped by field+value.
  const suggestSeen = new Set();
  const suggestedAliases = [];

  rows.forEach((data, i) => {
    const v = validateRecord(data, i, entity);
    if (!v.valid) {
      rejected.push({ row: i, errors: v.errors, data });
      for (const e of v.errors) {
        if (e.code !== "not_in_options") continue;
        const key = `${e.field}=${e.value}`;
        if (suggestSeen.has(key)) continue;
        suggestSeen.add(key);
        suggestedAliases.push({
          entity,
          field: e.field,
          value: e.value,
          options: (rulesByEntity[entity]?.[e.field]?.values) || [],
          institution: data.institution || null,
        });
      }
      return;
    }

    // RULI: CSPRNG code + salt + verification hash
    const code = generateCode();
    const salt = generateSalt();
    const hash = hashCode(code, salt);

    // safe -> dash record ; sensitive -> mapping ONLY
    const { safe, sensitive } = splitSensitive(data, entity);

    const metadata = buildMetadata({ code, salt, hash, rowIndex: i, createdAt: when, entity });
    const tables = buildTables(safe, { code, salt, entity });

    accepted.push({
      record: buildRecord({ code, metadata, entity, data: safe, tables }),
      mapping: { RULI: code, salt, [entity]: sensitive },
      identityHash: identityHash(data, entity),
    });
  });

  return {
    entity,
    total: rows.length,
    accepted,
    rejected,
    headerAliasesApplied: norm.applied,
    valueAliasesApplied: vals.applied,
    dateNormalizationApplied: dts.applied,
    suggestedAliases,
    headerWarnings,
    batchError: null,
  };
}
