import { NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";
import { processRows } from "@/lib/ingestPipeline";

const OUT_DIR = path.join(process.cwd(), "data", "output");

// 120 synthetic teaching-staff records across 5 OECS territories, 10 institutions.
// All values are strings (matching CSV-parsed input the pipeline expects).
// PII fields (surname, first_name, date_of_birth, nationality) go to mapping only.
//
// NOTE on codes: the human-readable values below (classification "PR"/"TT",
// highest_qualification "PhD"/"Masters"/...) are NOT the canonical RMR codes.
// lib/valueAliases.js normalizes them on the way in (e.g. PR->PRIN, TT->LECT,
// PhD->PHD, Masters->MAST, PostGradDiploma->PGD, Bachelors->BACH, Diploma->DIP),
// so stored records carry RMR codes and the SDG math (MIN_QUALIFICATIONS in
// RMR codes) still computes. No need to edit the rows by hand.
//
// SEEDED DISCREPANCIES (for the flag -> approve demo): 4 Monroe College LC rows
// carry sex="Male"/"Female" (Nestor, Thomas = Male; Odlum, Quashie = Female).
// Those full words are intentionally OMITTED from staff sex aliases in
// lib/valueAliases.js, so the pipeline rejects them as not_in_options -> they
// surface as suggestions an admin approves (Male->M / Female->F).
const DEMO_ROWS = [
  // --- Kingston Community College, Jamaica (12) ---
  { institution:"Kingston Community College", territory:"Jamaica", surname:"Brown", first_name:"Sophia", sex:"F", classification:"PR", highest_qualification:"PhD", years_experience:"18", cpd_hours:"45", left_service:"N", appraised:"Y", date_of_birth:"1972-04-12", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Educational Leadership", area_of_specialisation:"Educational Leadership", total_periods:"15" },
  { institution:"Kingston Community College", territory:"Jamaica", surname:"Williams", first_name:"David", sex:"M", classification:"VP", highest_qualification:"Masters", years_experience:"14", cpd_hours:"32", left_service:"N", appraised:"Y", date_of_birth:"1976-08-23", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Mathematics", area_of_specialisation:"STEM", total_periods:"18" },
  { institution:"Kingston Community College", territory:"Jamaica", surname:"Joseph", first_name:"Angela", sex:"F", classification:"HOD", highest_qualification:"Masters", years_experience:"11", cpd_hours:"25", left_service:"N", appraised:"Y", date_of_birth:"1979-11-05", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Biology", area_of_specialisation:"Health Sciences", total_periods:"24" },
  { institution:"Kingston Community College", territory:"Jamaica", surname:"Clarke", first_name:"Marcus", sex:"M", classification:"HOD", highest_qualification:"Bachelors", years_experience:"9", cpd_hours:"18", left_service:"N", appraised:"Y", date_of_birth:"1981-03-17", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Computer Science", area_of_specialisation:"Technology", total_periods:"28" },
  { institution:"Kingston Community College", territory:"Jamaica", surname:"Thomas", first_name:"Karen", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"6", cpd_hours:"12", left_service:"N", appraised:"Y", date_of_birth:"1984-07-30", nationality:"Jamaican", teacher_type:"Full Time", subjects:"English Language", area_of_specialisation:"Humanities", total_periods:"30" },
  { institution:"Kingston Community College", territory:"Jamaica", surname:"Lewis", first_name:"Ricardo", sex:"M", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"4", cpd_hours:"8", left_service:"N", appraised:"N", date_of_birth:"1986-12-14", nationality:"Jamaican", teacher_type:"Full Time", subjects:"History", area_of_specialisation:"Social Sciences", total_periods:"26" },
  { institution:"Kingston Community College", territory:"Jamaica", surname:"Francis", first_name:"Donna", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"7", cpd_hours:"0", left_service:"N", appraised:"Y", date_of_birth:"1983-05-28", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Spanish", area_of_specialisation:"Languages", total_periods:"28" },
  { institution:"Kingston Community College", territory:"Jamaica", surname:"Campbell", first_name:"Wayne", sex:"M", classification:"TT", highest_qualification:"Diploma", years_experience:"3", cpd_hours:"0", left_service:"Y", appraised:"N", date_of_birth:"1987-09-11", nationality:"Jamaican", teacher_type:"Part Time", subjects:"Art & Design", area_of_specialisation:"Creative Arts", total_periods:"16" },
  { institution:"Kingston Community College", territory:"Jamaica", surname:"Richards", first_name:"Maxine", sex:"F", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"5", cpd_hours:"20", left_service:"N", appraised:"Y", date_of_birth:"1985-02-19", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Accounting", area_of_specialisation:"Business & Finance", total_periods:"30" },
  { institution:"Kingston Community College", territory:"Jamaica", surname:"Robinson", first_name:"Gerald", sex:"M", classification:"TT", highest_qualification:"Masters", years_experience:"22", cpd_hours:"40", left_service:"N", appraised:"Y", date_of_birth:"1968-06-07", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Economics", area_of_specialisation:"Business & Finance", total_periods:"28" },
  { institution:"Kingston Community College", territory:"Jamaica", surname:"Edwards", first_name:"Patricia", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"1", cpd_hours:"5", left_service:"N", appraised:"N", date_of_birth:"1989-10-23", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Chemistry", area_of_specialisation:"STEM", total_periods:"24" },
  { institution:"Kingston Community College", territory:"Jamaica", surname:"Mitchell", first_name:"Calvin", sex:"M", classification:"TT", highest_qualification:"CAPE", years_experience:"2", cpd_hours:"10", left_service:"N", appraised:"N", date_of_birth:"1988-04-15", nationality:"Jamaican", teacher_type:"Contract", subjects:"Physical Education", area_of_specialisation:"Health Sciences", total_periods:"20" },

  // --- Montego Bay Teachers College, Jamaica (12) ---
  { institution:"Montego Bay Teachers College", territory:"Jamaica", surname:"James", first_name:"Sandra", sex:"F", classification:"PR", highest_qualification:"PhD", years_experience:"21", cpd_hours:"50", left_service:"N", appraised:"Y", date_of_birth:"1969-03-08", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Educational Leadership", area_of_specialisation:"Educational Leadership", total_periods:"12" },
  { institution:"Montego Bay Teachers College", territory:"Jamaica", surname:"Alexander", first_name:"Byron", sex:"M", classification:"VP", highest_qualification:"Masters", years_experience:"16", cpd_hours:"35", left_service:"N", appraised:"Y", date_of_birth:"1974-07-22", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Mathematics", area_of_specialisation:"STEM", total_periods:"16" },
  { institution:"Montego Bay Teachers College", territory:"Jamaica", surname:"Charles", first_name:"Stacey", sex:"F", classification:"HOD", highest_qualification:"Masters", years_experience:"12", cpd_hours:"28", left_service:"N", appraised:"Y", date_of_birth:"1978-11-14", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Science", area_of_specialisation:"STEM", total_periods:"22" },
  { institution:"Montego Bay Teachers College", territory:"Jamaica", surname:"Antoine", first_name:"Winston", sex:"M", classification:"HOD", highest_qualification:"Bachelors", years_experience:"8", cpd_hours:"15", left_service:"N", appraised:"Y", date_of_birth:"1982-05-03", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Geography", area_of_specialisation:"Social Sciences", total_periods:"26" },
  { institution:"Montego Bay Teachers College", territory:"Jamaica", surname:"Phillip", first_name:"Michelle", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"5", cpd_hours:"8", left_service:"N", appraised:"Y", date_of_birth:"1985-08-18", nationality:"Jamaican", teacher_type:"Full Time", subjects:"English Language", area_of_specialisation:"Humanities", total_periods:"30" },
  { institution:"Montego Bay Teachers College", territory:"Jamaica", surname:"Gabriel", first_name:"Clive", sex:"M", classification:"TT", highest_qualification:"Diploma", years_experience:"3", cpd_hours:"0", left_service:"N", appraised:"N", date_of_birth:"1987-12-05", nationality:"Jamaican", teacher_type:"Part Time", subjects:"Music", area_of_specialisation:"Creative Arts", total_periods:"18" },
  { institution:"Montego Bay Teachers College", territory:"Jamaica", surname:"Pierre", first_name:"Alicia", sex:"F", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"6", cpd_hours:"22", left_service:"N", appraised:"Y", date_of_birth:"1984-04-25", nationality:"Jamaican", teacher_type:"Full Time", subjects:"French", area_of_specialisation:"Languages", total_periods:"28" },
  { institution:"Montego Bay Teachers College", territory:"Jamaica", surname:"Baptiste", first_name:"Curtis", sex:"M", classification:"TT", highest_qualification:"Bachelors", years_experience:"10", cpd_hours:"30", left_service:"N", appraised:"Y", date_of_birth:"1980-09-17", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Information Technology", area_of_specialisation:"Technology", total_periods:"28" },
  { institution:"Montego Bay Teachers College", territory:"Jamaica", surname:"Sewell", first_name:"Cheryl", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"4", cpd_hours:"6", left_service:"N", appraised:"N", date_of_birth:"1986-01-29", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Business Studies", area_of_specialisation:"Business & Finance", total_periods:"28" },
  { institution:"Montego Bay Teachers College", territory:"Jamaica", surname:"Dawson", first_name:"Ivan", sex:"M", classification:"TT", highest_qualification:"Masters", years_experience:"28", cpd_hours:"45", left_service:"N", appraised:"Y", date_of_birth:"1962-06-14", nationality:"Jamaican", teacher_type:"Full Time", subjects:"History", area_of_specialisation:"Social Sciences", total_periods:"24" },
  { institution:"Montego Bay Teachers College", territory:"Jamaica", surname:"Green", first_name:"Nadine", sex:"F", classification:"TT", highest_qualification:"CAPE", years_experience:"1", cpd_hours:"4", left_service:"Y", appraised:"N", date_of_birth:"1989-03-11", nationality:"Jamaican", teacher_type:"Contract", subjects:"Environmental Science", area_of_specialisation:"Environmental Studies", total_periods:"20" },
  { institution:"Montego Bay Teachers College", territory:"Jamaica", surname:"Morrison", first_name:"Norman", sex:"M", classification:"TT", highest_qualification:"Diploma", years_experience:"7", cpd_hours:"0", left_service:"N", appraised:"Y", date_of_birth:"1983-10-22", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Social Studies", area_of_specialisation:"Social Sciences", total_periods:"26" },

  // --- Northern Caribbean University, Jamaica (12) ---
  { institution:"Northern Caribbean University", territory:"Jamaica", surname:"Palmer", first_name:"Theresa", sex:"F", classification:"PR", highest_qualification:"PhD", years_experience:"26", cpd_hours:"55", left_service:"N", appraised:"Y", date_of_birth:"1964-05-17", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Educational Administration", area_of_specialisation:"Educational Leadership", total_periods:"10" },
  { institution:"Northern Caribbean University", territory:"Jamaica", surname:"Reid", first_name:"Patrick", sex:"M", classification:"VP", highest_qualification:"PhD", years_experience:"19", cpd_hours:"42", left_service:"N", appraised:"Y", date_of_birth:"1971-09-04", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Research Methods", area_of_specialisation:"Social Sciences", total_periods:"14" },
  { institution:"Northern Caribbean University", territory:"Jamaica", surname:"Bennett", first_name:"Lydia", sex:"F", classification:"HOD", highest_qualification:"Masters", years_experience:"14", cpd_hours:"33", left_service:"N", appraised:"Y", date_of_birth:"1976-02-28", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Nursing", area_of_specialisation:"Health Sciences", total_periods:"22" },
  { institution:"Northern Caribbean University", territory:"Jamaica", surname:"McKenzie", first_name:"Stanley", sex:"M", classification:"HOD", highest_qualification:"Masters", years_experience:"10", cpd_hours:"24", left_service:"N", appraised:"Y", date_of_birth:"1980-07-15", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Computer Science", area_of_specialisation:"Technology", total_periods:"24" },
  { institution:"Northern Caribbean University", territory:"Jamaica", surname:"Allen", first_name:"Janet", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"7", cpd_hours:"14", left_service:"N", appraised:"Y", date_of_birth:"1983-12-09", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Biology", area_of_specialisation:"STEM", total_periods:"28" },
  { institution:"Northern Caribbean University", territory:"Jamaica", surname:"Barrett", first_name:"Derek", sex:"M", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"5", cpd_hours:"10", left_service:"N", appraised:"N", date_of_birth:"1985-04-21", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Mathematics", area_of_specialisation:"STEM", total_periods:"28" },
  { institution:"Northern Caribbean University", territory:"Jamaica", surname:"Cooke", first_name:"Monica", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"3", cpd_hours:"6", left_service:"N", appraised:"N", date_of_birth:"1987-08-13", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Psychology", area_of_specialisation:"Social Sciences", total_periods:"26" },
  { institution:"Northern Caribbean University", territory:"Jamaica", surname:"Douglas", first_name:"Clarence", sex:"M", classification:"TT", highest_qualification:"Bachelors", years_experience:"2", cpd_hours:"5", left_service:"N", appraised:"N", date_of_birth:"1988-03-07", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Accounting", area_of_specialisation:"Business & Finance", total_periods:"28" },
  { institution:"Northern Caribbean University", territory:"Jamaica", surname:"Ellis", first_name:"Deborah", sex:"F", classification:"TT", highest_qualification:"Masters", years_experience:"30", cpd_hours:"50", left_service:"N", appraised:"Y", date_of_birth:"1960-11-30", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Theology", area_of_specialisation:"Humanities", total_periods:"22" },
  { institution:"Northern Caribbean University", territory:"Jamaica", surname:"Forbes", first_name:"Anthony", sex:"M", classification:"TT", highest_qualification:"Diploma", years_experience:"4", cpd_hours:"0", left_service:"N", appraised:"Y", date_of_birth:"1986-06-25", nationality:"Jamaican", teacher_type:"Part Time", subjects:"Music", area_of_specialisation:"Creative Arts", total_periods:"16" },
  { institution:"Northern Caribbean University", territory:"Jamaica", surname:"Gordon", first_name:"Priya", sex:"F", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"8", cpd_hours:"18", left_service:"Y", appraised:"Y", date_of_birth:"1982-01-17", nationality:"Jamaican", teacher_type:"Full Time", subjects:"Chemistry", area_of_specialisation:"STEM", total_periods:"26" },
  { institution:"Northern Caribbean University", territory:"Jamaica", surname:"Henry", first_name:"Michael", sex:"M", classification:"TT", highest_qualification:"CAPE", years_experience:"1", cpd_hours:"3", left_service:"N", appraised:"N", date_of_birth:"1989-09-28", nationality:"Jamaican", teacher_type:"Contract", subjects:"Physical Education", area_of_specialisation:"Health Sciences", total_periods:"20" },

  // --- Sir Arthur Lewis Community College, Saint Lucia (12) ---
  { institution:"Sir Arthur Lewis Community College", territory:"Saint Lucia", surname:"Augustin", first_name:"Marie", sex:"F", classification:"PR", highest_qualification:"PhD", years_experience:"23", cpd_hours:"48", left_service:"N", appraised:"Y", date_of_birth:"1967-07-14", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Educational Administration", area_of_specialisation:"Educational Leadership", total_periods:"12" },
  { institution:"Sir Arthur Lewis Community College", territory:"Saint Lucia", surname:"Cornibert", first_name:"Andre", sex:"M", classification:"VP", highest_qualification:"Masters", years_experience:"17", cpd_hours:"38", left_service:"N", appraised:"Y", date_of_birth:"1973-11-27", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Economics", area_of_specialisation:"Business & Finance", total_periods:"16" },
  { institution:"Sir Arthur Lewis Community College", territory:"Saint Lucia", surname:"Gustave", first_name:"Sandra", sex:"F", classification:"HOD", highest_qualification:"Masters", years_experience:"13", cpd_hours:"27", left_service:"N", appraised:"Y", date_of_birth:"1977-04-09", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Biology", area_of_specialisation:"STEM", total_periods:"22" },
  { institution:"Sir Arthur Lewis Community College", territory:"Saint Lucia", surname:"Mathurin", first_name:"Lennox", sex:"M", classification:"HOD", highest_qualification:"Bachelors", years_experience:"9", cpd_hours:"16", left_service:"N", appraised:"Y", date_of_birth:"1981-08-20", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Physics", area_of_specialisation:"STEM", total_periods:"26" },
  { institution:"Sir Arthur Lewis Community College", territory:"Saint Lucia", surname:"Popo", first_name:"Kezia", sex:"F", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"6", cpd_hours:"14", left_service:"N", appraised:"Y", date_of_birth:"1984-01-03", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"French", area_of_specialisation:"Languages", total_periods:"30" },
  { institution:"Sir Arthur Lewis Community College", territory:"Saint Lucia", surname:"Compton", first_name:"Clive", sex:"M", classification:"TT", highest_qualification:"Bachelors", years_experience:"4", cpd_hours:"7", left_service:"N", appraised:"N", date_of_birth:"1986-05-16", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"History", area_of_specialisation:"Social Sciences", total_periods:"28" },
  { institution:"Sir Arthur Lewis Community College", territory:"Saint Lucia", surname:"Emmanuel", first_name:"Angela", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"8", cpd_hours:"20", left_service:"N", appraised:"Y", date_of_birth:"1982-10-31", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Information Technology", area_of_specialisation:"Technology", total_periods:"28" },
  { institution:"Sir Arthur Lewis Community College", territory:"Saint Lucia", surname:"Fevrier", first_name:"Marcus", sex:"M", classification:"TT", highest_qualification:"Diploma", years_experience:"2", cpd_hours:"0", left_service:"N", appraised:"N", date_of_birth:"1988-07-08", nationality:"Saint Lucian", teacher_type:"Part Time", subjects:"Art & Design", area_of_specialisation:"Creative Arts", total_periods:"16" },
  { institution:"Sir Arthur Lewis Community College", territory:"Saint Lucia", surname:"George", first_name:"Karen", sex:"F", classification:"TT", highest_qualification:"Masters", years_experience:"25", cpd_hours:"45", left_service:"N", appraised:"Y", date_of_birth:"1965-03-22", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"English Literature", area_of_specialisation:"Humanities", total_periods:"24" },
  { institution:"Sir Arthur Lewis Community College", territory:"Saint Lucia", surname:"Hippolyte", first_name:"Wayne", sex:"M", classification:"TT", highest_qualification:"Bachelors", years_experience:"5", cpd_hours:"10", left_service:"N", appraised:"Y", date_of_birth:"1985-11-14", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Mathematics", area_of_specialisation:"STEM", total_periods:"30" },
  { institution:"Sir Arthur Lewis Community College", territory:"Saint Lucia", surname:"Inglis", first_name:"Donna", sex:"F", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"3", cpd_hours:"8", left_service:"Y", appraised:"N", date_of_birth:"1987-06-05", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Social Studies", area_of_specialisation:"Social Sciences", total_periods:"26" },
  { institution:"Sir Arthur Lewis Community College", territory:"Saint Lucia", surname:"Jn Baptiste", first_name:"Ricardo", sex:"M", classification:"TT", highest_qualification:"CAPE", years_experience:"1", cpd_hours:"4", left_service:"N", appraised:"N", date_of_birth:"1989-02-19", nationality:"Saint Lucian", teacher_type:"Contract", subjects:"Physical Education", area_of_specialisation:"Health Sciences", total_periods:"20" },

  // --- Monroe College LC, Saint Lucia (12) ---
  { institution:"Monroe College LC", territory:"Saint Lucia", surname:"Joseph", first_name:"Sophia", sex:"F", classification:"PR", highest_qualification:"PhD", years_experience:"20", cpd_hours:"46", left_service:"N", appraised:"Y", date_of_birth:"1970-08-28", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Business Administration", area_of_specialisation:"Business & Finance", total_periods:"12" },
  { institution:"Monroe College LC", territory:"Saint Lucia", surname:"Louisy", first_name:"Calvin", sex:"M", classification:"VP", highest_qualification:"Masters", years_experience:"15", cpd_hours:"34", left_service:"N", appraised:"Y", date_of_birth:"1975-12-11", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Hospitality Management", area_of_specialisation:"Business & Finance", total_periods:"16" },
  { institution:"Monroe College LC", territory:"Saint Lucia", surname:"Monplaisir", first_name:"Michelle", sex:"F", classification:"HOD", highest_qualification:"Masters", years_experience:"11", cpd_hours:"25", left_service:"N", appraised:"Y", date_of_birth:"1979-05-04", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Computer Science", area_of_specialisation:"Technology", total_periods:"24" },
  { institution:"Monroe College LC", territory:"Saint Lucia", surname:"Nestor", first_name:"Gerald", sex:"Male", classification:"TT", highest_qualification:"Bachelors", years_experience:"7", cpd_hours:"14", left_service:"N", appraised:"Y", date_of_birth:"1983-09-17", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Mathematics", area_of_specialisation:"STEM", total_periods:"28" },
  { institution:"Monroe College LC", territory:"Saint Lucia", surname:"Odlum", first_name:"Patricia", sex:"Female", classification:"TT", highest_qualification:"Bachelors", years_experience:"5", cpd_hours:"8", left_service:"N", appraised:"Y", date_of_birth:"1985-03-26", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"English Language", area_of_specialisation:"Humanities", total_periods:"30" },
  { institution:"Monroe College LC", territory:"Saint Lucia", surname:"Phillip", first_name:"Byron", sex:"M", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"9", cpd_hours:"20", left_service:"N", appraised:"Y", date_of_birth:"1981-07-13", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Economics", area_of_specialisation:"Business & Finance", total_periods:"28" },
  { institution:"Monroe College LC", territory:"Saint Lucia", surname:"Quashie", first_name:"Stacey", sex:"Female", classification:"TT", highest_qualification:"Bachelors", years_experience:"3", cpd_hours:"6", left_service:"N", appraised:"N", date_of_birth:"1987-01-24", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Tourism", area_of_specialisation:"Business & Finance", total_periods:"26" },
  { institution:"Monroe College LC", territory:"Saint Lucia", surname:"Renard", first_name:"Clive", sex:"M", classification:"TT", highest_qualification:"Diploma", years_experience:"2", cpd_hours:"0", left_service:"N", appraised:"N", date_of_birth:"1988-10-07", nationality:"Saint Lucian", teacher_type:"Part Time", subjects:"Sport Science", area_of_specialisation:"Health Sciences", total_periods:"16" },
  { institution:"Monroe College LC", territory:"Saint Lucia", surname:"Simon", first_name:"Cheryl", sex:"F", classification:"TT", highest_qualification:"Masters", years_experience:"18", cpd_hours:"40", left_service:"N", appraised:"Y", date_of_birth:"1972-06-30", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Accounting", area_of_specialisation:"Business & Finance", total_periods:"24" },
  { institution:"Monroe College LC", territory:"Saint Lucia", surname:"Thomas", first_name:"Anthony", sex:"Male", classification:"TT", highest_qualification:"Bachelors", years_experience:"6", cpd_hours:"12", left_service:"N", appraised:"Y", date_of_birth:"1984-04-18", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Marketing", area_of_specialisation:"Business & Finance", total_periods:"28" },
  { institution:"Monroe College LC", territory:"Saint Lucia", surname:"Ulric", first_name:"Nadine", sex:"F", classification:"TT", highest_qualification:"Diploma", years_experience:"4", cpd_hours:"0", left_service:"Y", appraised:"N", date_of_birth:"1986-11-05", nationality:"Saint Lucian", teacher_type:"Part Time", subjects:"Culinary Arts", area_of_specialisation:"Creative Arts", total_periods:"18" },
  { institution:"Monroe College LC", territory:"Saint Lucia", surname:"Valcin", first_name:"Derek", sex:"M", classification:"TT", highest_qualification:"Bachelors", years_experience:"12", cpd_hours:"22", left_service:"N", appraised:"Y", date_of_birth:"1978-02-14", nationality:"Saint Lucian", teacher_type:"Full Time", subjects:"Information Technology", area_of_specialisation:"Technology", total_periods:"28" },

  // --- Samuel Jackman Prescod Polytechnic, Barbados (12) ---
  { institution:"Samuel Jackman Prescod Polytechnic", territory:"Barbados", surname:"Barrow", first_name:"Maxine", sex:"F", classification:"PR", highest_qualification:"PhD", years_experience:"24", cpd_hours:"52", left_service:"N", appraised:"Y", date_of_birth:"1966-09-11", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Engineering", area_of_specialisation:"STEM", total_periods:"10" },
  { institution:"Samuel Jackman Prescod Polytechnic", territory:"Barbados", surname:"Beckles", first_name:"Carlisle", sex:"M", classification:"VP", highest_qualification:"Masters", years_experience:"18", cpd_hours:"40", left_service:"N", appraised:"Y", date_of_birth:"1972-01-24", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Electronics", area_of_specialisation:"Technology", total_periods:"16" },
  { institution:"Samuel Jackman Prescod Polytechnic", territory:"Barbados", surname:"Caddle", first_name:"Sharon", sex:"F", classification:"HOD", highest_qualification:"Masters", years_experience:"14", cpd_hours:"30", left_service:"N", appraised:"Y", date_of_birth:"1976-06-07", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Applied Chemistry", area_of_specialisation:"STEM", total_periods:"22" },
  { institution:"Samuel Jackman Prescod Polytechnic", territory:"Barbados", surname:"Drakes", first_name:"Donovan", sex:"M", classification:"HOD", highest_qualification:"Bachelors", years_experience:"10", cpd_hours:"18", left_service:"N", appraised:"Y", date_of_birth:"1980-10-19", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Mechanical Engineering", area_of_specialisation:"Technology", total_periods:"26" },
  { institution:"Samuel Jackman Prescod Polytechnic", territory:"Barbados", surname:"Edwards", first_name:"Roslyn", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"6", cpd_hours:"12", left_service:"N", appraised:"Y", date_of_birth:"1984-03-03", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Mathematics", area_of_specialisation:"STEM", total_periods:"30" },
  { institution:"Samuel Jackman Prescod Polytechnic", territory:"Barbados", surname:"Forde", first_name:"Grantley", sex:"M", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"5", cpd_hours:"10", left_service:"N", appraised:"N", date_of_birth:"1985-07-28", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Computer Networking", area_of_specialisation:"Technology", total_periods:"28" },
  { institution:"Samuel Jackman Prescod Polytechnic", territory:"Barbados", surname:"Greenidge", first_name:"Evelyn", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"3", cpd_hours:"6", left_service:"N", appraised:"N", date_of_birth:"1987-11-22", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Building Technology", area_of_specialisation:"Technology", total_periods:"26" },
  { institution:"Samuel Jackman Prescod Polytechnic", territory:"Barbados", surname:"Hunte", first_name:"Keith", sex:"M", classification:"TT", highest_qualification:"Diploma", years_experience:"2", cpd_hours:"0", left_service:"N", appraised:"N", date_of_birth:"1988-05-09", nationality:"Barbadian", teacher_type:"Part Time", subjects:"Welding", area_of_specialisation:"Technology", total_periods:"18" },
  { institution:"Samuel Jackman Prescod Polytechnic", territory:"Barbados", surname:"Inniss", first_name:"Felicia", sex:"F", classification:"TT", highest_qualification:"Masters", years_experience:"22", cpd_hours:"44", left_service:"N", appraised:"Y", date_of_birth:"1968-08-16", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Business Studies", area_of_specialisation:"Business & Finance", total_periods:"24" },
  { institution:"Samuel Jackman Prescod Polytechnic", territory:"Barbados", surname:"Jordan", first_name:"Errol", sex:"M", classification:"TT", highest_qualification:"Bachelors", years_experience:"8", cpd_hours:"16", left_service:"N", appraised:"Y", date_of_birth:"1982-12-30", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Electrical Engineering", area_of_specialisation:"Technology", total_periods:"28" },
  { institution:"Samuel Jackman Prescod Polytechnic", territory:"Barbados", surname:"King", first_name:"Tricia", sex:"F", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"4", cpd_hours:"8", left_service:"Y", appraised:"Y", date_of_birth:"1986-04-14", nationality:"Barbadian", teacher_type:"Full Time", subjects:"English Language", area_of_specialisation:"Humanities", total_periods:"28" },
  { institution:"Samuel Jackman Prescod Polytechnic", territory:"Barbados", surname:"Lashley", first_name:"Norman", sex:"M", classification:"TT", highest_qualification:"CAPE", years_experience:"1", cpd_hours:"3", left_service:"N", appraised:"N", date_of_birth:"1989-01-27", nationality:"Barbadian", teacher_type:"Contract", subjects:"Automotive Technology", area_of_specialisation:"Technology", total_periods:"20" },

  // --- Community College of Barbados (12) ---
  { institution:"Community College of Barbados", territory:"Barbados", surname:"Mapp", first_name:"Donna", sex:"F", classification:"PR", highest_qualification:"PhD", years_experience:"27", cpd_hours:"56", left_service:"N", appraised:"Y", date_of_birth:"1963-10-05", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Educational Leadership", area_of_specialisation:"Educational Leadership", total_periods:"10" },
  { institution:"Community College of Barbados", territory:"Barbados", surname:"Niles", first_name:"Renwick", sex:"M", classification:"VP", highest_qualification:"Masters", years_experience:"20", cpd_hours:"43", left_service:"N", appraised:"Y", date_of_birth:"1970-02-18", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Economics", area_of_specialisation:"Business & Finance", total_periods:"14" },
  { institution:"Community College of Barbados", territory:"Barbados", surname:"Osbourne", first_name:"Cheryl", sex:"F", classification:"HOD", highest_qualification:"Masters", years_experience:"15", cpd_hours:"32", left_service:"N", appraised:"Y", date_of_birth:"1975-06-29", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Mathematics", area_of_specialisation:"STEM", total_periods:"22" },
  { institution:"Community College of Barbados", territory:"Barbados", surname:"Payne", first_name:"Selwyn", sex:"M", classification:"HOD", highest_qualification:"Bachelors", years_experience:"11", cpd_hours:"22", left_service:"N", appraised:"Y", date_of_birth:"1979-11-12", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Physics", area_of_specialisation:"STEM", total_periods:"24" },
  { institution:"Community College of Barbados", territory:"Barbados", surname:"Quansah", first_name:"Janet", sex:"F", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"7", cpd_hours:"16", left_service:"N", appraised:"Y", date_of_birth:"1983-04-08", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Chemistry", area_of_specialisation:"STEM", total_periods:"28" },
  { institution:"Community College of Barbados", territory:"Barbados", surname:"Roach", first_name:"Alphonso", sex:"M", classification:"TT", highest_qualification:"Bachelors", years_experience:"5", cpd_hours:"10", left_service:"N", appraised:"N", date_of_birth:"1985-09-21", nationality:"Barbadian", teacher_type:"Full Time", subjects:"History", area_of_specialisation:"Social Sciences", total_periods:"28" },
  { institution:"Community College of Barbados", territory:"Barbados", surname:"Skeete", first_name:"Alicia", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"3", cpd_hours:"7", left_service:"N", appraised:"N", date_of_birth:"1987-02-14", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Spanish", area_of_specialisation:"Languages", total_periods:"28" },
  { institution:"Community College of Barbados", territory:"Barbados", surname:"Tudor", first_name:"Reginald", sex:"M", classification:"TT", highest_qualification:"Diploma", years_experience:"2", cpd_hours:"0", left_service:"N", appraised:"N", date_of_birth:"1988-06-26", nationality:"Barbadian", teacher_type:"Part Time", subjects:"Geography", area_of_specialisation:"Social Sciences", total_periods:"16" },
  { institution:"Community College of Barbados", territory:"Barbados", surname:"Utter", first_name:"Maxine", sex:"F", classification:"TT", highest_qualification:"Masters", years_experience:"24", cpd_hours:"48", left_service:"N", appraised:"Y", date_of_birth:"1966-01-17", nationality:"Barbadian", teacher_type:"Full Time", subjects:"English Literature", area_of_specialisation:"Humanities", total_periods:"22" },
  { institution:"Community College of Barbados", territory:"Barbados", surname:"Vaughan", first_name:"Winston", sex:"M", classification:"TT", highest_qualification:"Bachelors", years_experience:"9", cpd_hours:"18", left_service:"N", appraised:"Y", date_of_birth:"1981-07-04", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Accounting", area_of_specialisation:"Business & Finance", total_periods:"28" },
  { institution:"Community College of Barbados", territory:"Barbados", surname:"Waithe", first_name:"Serena", sex:"F", classification:"TT", highest_qualification:"CAPE", years_experience:"1", cpd_hours:"4", left_service:"Y", appraised:"N", date_of_birth:"1989-12-20", nationality:"Barbadian", teacher_type:"Contract", subjects:"Art & Design", area_of_specialisation:"Creative Arts", total_periods:"18" },
  { institution:"Community College of Barbados", territory:"Barbados", surname:"Yearwood", first_name:"Marcus", sex:"M", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"6", cpd_hours:"14", left_service:"N", appraised:"Y", date_of_birth:"1984-05-07", nationality:"Barbadian", teacher_type:"Full Time", subjects:"Information Technology", area_of_specialisation:"Technology", total_periods:"26" },

  // --- COSTAATT, Trinidad and Tobago (12) ---
  { institution:"COSTAATT", territory:"Trinidad and Tobago", surname:"Achong", first_name:"Priya", sex:"F", classification:"PR", highest_qualification:"PhD", years_experience:"22", cpd_hours:"50", left_service:"N", appraised:"Y", date_of_birth:"1968-07-15", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Business Administration", area_of_specialisation:"Business & Finance", total_periods:"12" },
  { institution:"COSTAATT", territory:"Trinidad and Tobago", surname:"Baptiste", first_name:"Rhondal", sex:"M", classification:"VP", highest_qualification:"Masters", years_experience:"16", cpd_hours:"36", left_service:"N", appraised:"Y", date_of_birth:"1974-11-28", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Management", area_of_specialisation:"Business & Finance", total_periods:"16" },
  { institution:"COSTAATT", territory:"Trinidad and Tobago", surname:"Chatoor", first_name:"Kavitha", sex:"F", classification:"HOD", highest_qualification:"Masters", years_experience:"12", cpd_hours:"26", left_service:"N", appraised:"Y", date_of_birth:"1978-03-19", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Accounting", area_of_specialisation:"Business & Finance", total_periods:"24" },
  { institution:"COSTAATT", territory:"Trinidad and Tobago", surname:"Dindial", first_name:"Rishi", sex:"M", classification:"HOD", highest_qualification:"Bachelors", years_experience:"8", cpd_hours:"16", left_service:"N", appraised:"Y", date_of_birth:"1982-08-01", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Computer Science", area_of_specialisation:"Technology", total_periods:"26" },
  { institution:"COSTAATT", territory:"Trinidad and Tobago", surname:"Emmanuel", first_name:"Lakeisha", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"6", cpd_hours:"12", left_service:"N", appraised:"Y", date_of_birth:"1984-12-14", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Mathematics", area_of_specialisation:"STEM", total_periods:"28" },
  { institution:"COSTAATT", territory:"Trinidad and Tobago", surname:"Farray", first_name:"Carlton", sex:"M", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"4", cpd_hours:"8", left_service:"N", appraised:"N", date_of_birth:"1986-05-08", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Economics", area_of_specialisation:"Business & Finance", total_periods:"28" },
  { institution:"COSTAATT", territory:"Trinidad and Tobago", surname:"Gobin", first_name:"Anita", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"3", cpd_hours:"6", left_service:"N", appraised:"N", date_of_birth:"1987-09-22", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Sociology", area_of_specialisation:"Social Sciences", total_periods:"28" },
  { institution:"COSTAATT", territory:"Trinidad and Tobago", surname:"Hector", first_name:"Fabian", sex:"M", classification:"TT", highest_qualification:"Diploma", years_experience:"2", cpd_hours:"0", left_service:"N", appraised:"N", date_of_birth:"1988-02-11", nationality:"Trinidadian", teacher_type:"Part Time", subjects:"Technical Drawing", area_of_specialisation:"Technology", total_periods:"16" },
  { institution:"COSTAATT", territory:"Trinidad and Tobago", surname:"Ibrahim", first_name:"Zainab", sex:"F", classification:"TT", highest_qualification:"Masters", years_experience:"20", cpd_hours:"42", left_service:"N", appraised:"Y", date_of_birth:"1970-06-28", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"English Language", area_of_specialisation:"Humanities", total_periods:"22" },
  { institution:"COSTAATT", territory:"Trinidad and Tobago", surname:"Julien", first_name:"Darryl", sex:"M", classification:"TT", highest_qualification:"Bachelors", years_experience:"7", cpd_hours:"14", left_service:"N", appraised:"Y", date_of_birth:"1983-10-05", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Physics", area_of_specialisation:"STEM", total_periods:"28" },
  { institution:"COSTAATT", territory:"Trinidad and Tobago", surname:"Khan", first_name:"Reshma", sex:"F", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"5", cpd_hours:"10", left_service:"Y", appraised:"Y", date_of_birth:"1985-04-17", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Biology", area_of_specialisation:"STEM", total_periods:"26" },
  { institution:"COSTAATT", territory:"Trinidad and Tobago", surname:"Lopez", first_name:"Rondell", sex:"M", classification:"TT", highest_qualification:"CAPE", years_experience:"1", cpd_hours:"4", left_service:"N", appraised:"N", date_of_birth:"1989-07-31", nationality:"Trinidadian", teacher_type:"Contract", subjects:"Media Studies", area_of_specialisation:"Humanities", total_periods:"20" },

  // --- UTT San Fernando, Trinidad and Tobago (12) ---
  { institution:"UTT San Fernando", territory:"Trinidad and Tobago", surname:"Mohammed", first_name:"Fatimah", sex:"F", classification:"PR", highest_qualification:"PhD", years_experience:"25", cpd_hours:"54", left_service:"N", appraised:"Y", date_of_birth:"1965-11-22", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Chemical Engineering", area_of_specialisation:"STEM", total_periods:"10" },
  { institution:"UTT San Fernando", territory:"Trinidad and Tobago", surname:"Narine", first_name:"Vijay", sex:"M", classification:"VP", highest_qualification:"PhD", years_experience:"20", cpd_hours:"45", left_service:"N", appraised:"Y", date_of_birth:"1970-03-15", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Mathematics", area_of_specialisation:"STEM", total_periods:"14" },
  { institution:"UTT San Fernando", territory:"Trinidad and Tobago", surname:"Olton", first_name:"Camille", sex:"F", classification:"HOD", highest_qualification:"Masters", years_experience:"13", cpd_hours:"28", left_service:"N", appraised:"Y", date_of_birth:"1977-07-08", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Civil Engineering", area_of_specialisation:"Technology", total_periods:"22" },
  { institution:"UTT San Fernando", territory:"Trinidad and Tobago", surname:"Persad", first_name:"Devan", sex:"M", classification:"HOD", highest_qualification:"Masters", years_experience:"10", cpd_hours:"22", left_service:"N", appraised:"Y", date_of_birth:"1980-12-01", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Electrical Engineering", area_of_specialisation:"Technology", total_periods:"24" },
  { institution:"UTT San Fernando", territory:"Trinidad and Tobago", surname:"Ramkissoon", first_name:"Sushila", sex:"F", classification:"TT", highest_qualification:"Masters", years_experience:"8", cpd_hours:"18", left_service:"N", appraised:"Y", date_of_birth:"1982-05-24", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Computer Science", area_of_specialisation:"Technology", total_periods:"28" },
  { institution:"UTT San Fernando", territory:"Trinidad and Tobago", surname:"Seepersad", first_name:"Rajiv", sex:"M", classification:"TT", highest_qualification:"Bachelors", years_experience:"6", cpd_hours:"12", left_service:"N", appraised:"N", date_of_birth:"1984-09-17", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Mathematics", area_of_specialisation:"STEM", total_periods:"28" },
  { institution:"UTT San Fernando", territory:"Trinidad and Tobago", surname:"Telesford", first_name:"Simone", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"4", cpd_hours:"8", left_service:"N", appraised:"N", date_of_birth:"1986-02-06", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Chemistry", area_of_specialisation:"STEM", total_periods:"26" },
  { institution:"UTT San Fernando", territory:"Trinidad and Tobago", surname:"Usman", first_name:"Kareem", sex:"M", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"3", cpd_hours:"6", left_service:"N", appraised:"N", date_of_birth:"1987-06-19", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Physics", area_of_specialisation:"STEM", total_periods:"26" },
  { institution:"UTT San Fernando", territory:"Trinidad and Tobago", surname:"Ventour", first_name:"Sheryl", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"30", cpd_hours:"50", left_service:"N", appraised:"Y", date_of_birth:"1960-01-13", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"English Language", area_of_specialisation:"Humanities", total_periods:"22" },
  { institution:"UTT San Fernando", territory:"Trinidad and Tobago", surname:"Wilson", first_name:"Gervase", sex:"M", classification:"TT", highest_qualification:"Diploma", years_experience:"2", cpd_hours:"0", left_service:"N", appraised:"N", date_of_birth:"1988-11-30", nationality:"Trinidadian", teacher_type:"Part Time", subjects:"Environmental Science", area_of_specialisation:"Environmental Studies", total_periods:"16" },
  { institution:"UTT San Fernando", territory:"Trinidad and Tobago", surname:"Xavier", first_name:"Lavinia", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"5", cpd_hours:"10", left_service:"Y", appraised:"Y", date_of_birth:"1985-08-27", nationality:"Trinidadian", teacher_type:"Full Time", subjects:"Sociology", area_of_specialisation:"Social Sciences", total_periods:"26" },
  { institution:"UTT San Fernando", territory:"Trinidad and Tobago", surname:"Yorke", first_name:"Desmond", sex:"M", classification:"TT", highest_qualification:"CAPE", years_experience:"1", cpd_hours:"3", left_service:"N", appraised:"N", date_of_birth:"1989-04-09", nationality:"Trinidadian", teacher_type:"Contract", subjects:"Technical Drawing", area_of_specialisation:"Technology", total_periods:"20" },

  // --- T.A. Marryshow Community College, Grenada (12) ---
  { institution:"T.A. Marryshow Community College", territory:"Grenada", surname:"Alexis", first_name:"Beverley", sex:"F", classification:"PR", highest_qualification:"PhD", years_experience:"21", cpd_hours:"47", left_service:"N", appraised:"Y", date_of_birth:"1969-08-30", nationality:"Grenadian", teacher_type:"Full Time", subjects:"Educational Administration", area_of_specialisation:"Educational Leadership", total_periods:"12" },
  { institution:"T.A. Marryshow Community College", territory:"Grenada", surname:"Belfon", first_name:"Eustace", sex:"M", classification:"VP", highest_qualification:"Masters", years_experience:"16", cpd_hours:"36", left_service:"N", appraised:"Y", date_of_birth:"1974-12-16", nationality:"Grenadian", teacher_type:"Full Time", subjects:"Sciences", area_of_specialisation:"STEM", total_periods:"16" },
  { institution:"T.A. Marryshow Community College", territory:"Grenada", surname:"Charles", first_name:"Nadira", sex:"F", classification:"HOD", highest_qualification:"Masters", years_experience:"12", cpd_hours:"27", left_service:"N", appraised:"Y", date_of_birth:"1978-05-03", nationality:"Grenadian", teacher_type:"Full Time", subjects:"Biology", area_of_specialisation:"STEM", total_periods:"24" },
  { institution:"T.A. Marryshow Community College", territory:"Grenada", surname:"Downes", first_name:"Kevin", sex:"M", classification:"HOD", highest_qualification:"Bachelors", years_experience:"9", cpd_hours:"18", left_service:"N", appraised:"Y", date_of_birth:"1981-10-20", nationality:"Grenadian", teacher_type:"Full Time", subjects:"Mathematics", area_of_specialisation:"STEM", total_periods:"26" },
  { institution:"T.A. Marryshow Community College", territory:"Grenada", surname:"Emmanuel", first_name:"Shirley", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"6", cpd_hours:"12", left_service:"N", appraised:"Y", date_of_birth:"1984-03-11", nationality:"Grenadian", teacher_type:"Full Time", subjects:"English Language", area_of_specialisation:"Humanities", total_periods:"30" },
  { institution:"T.A. Marryshow Community College", territory:"Grenada", surname:"Fedon", first_name:"Lancelot", sex:"M", classification:"TT", highest_qualification:"PostGradDiploma", years_experience:"4", cpd_hours:"8", left_service:"N", appraised:"N", date_of_birth:"1986-07-25", nationality:"Grenadian", teacher_type:"Full Time", subjects:"History", area_of_specialisation:"Social Sciences", total_periods:"28" },
  { institution:"T.A. Marryshow Community College", territory:"Grenada", surname:"George", first_name:"Cynthia", sex:"F", classification:"TT", highest_qualification:"Bachelors", years_experience:"8", cpd_hours:"16", left_service:"N", appraised:"Y", date_of_birth:"1982-01-14", nationality:"Grenadian", teacher_type:"Full Time", subjects:"Information Technology", area_of_specialisation:"Technology", total_periods:"28" },
  { institution:"T.A. Marryshow Community College", territory:"Grenada", surname:"Humphrey", first_name:"Gregory", sex:"M", classification:"TT", highest_qualification:"Diploma", years_experience:"3", cpd_hours:"0", left_service:"N", appraised:"N", date_of_birth:"1987-05-07", nationality:"Grenadian", teacher_type:"Part Time", subjects:"Carpentry", area_of_specialisation:"Technology", total_periods:"18" },
  { institution:"T.A. Marryshow Community College", territory:"Grenada", surname:"Isaac", first_name:"Claudette", sex:"F", classification:"TT", highest_qualification:"Masters", years_experience:"19", cpd_hours:"42", left_service:"N", appraised:"Y", date_of_birth:"1971-09-27", nationality:"Grenadian", teacher_type:"Full Time", subjects:"Business Studies", area_of_specialisation:"Business & Finance", total_periods:"24" },
  { institution:"T.A. Marryshow Community College", territory:"Grenada", surname:"John", first_name:"Rennie", sex:"M", classification:"TT", highest_qualification:"Bachelors", years_experience:"7", cpd_hours:"14", left_service:"N", appraised:"Y", date_of_birth:"1983-02-22", nationality:"Grenadian", teacher_type:"Full Time", subjects:"Accounting", area_of_specialisation:"Business & Finance", total_periods:"28" },
  { institution:"T.A. Marryshow Community College", territory:"Grenada", surname:"King", first_name:"Veronica", sex:"F", classification:"TT", highest_qualification:"Diploma", years_experience:"2", cpd_hours:"0", left_service:"Y", appraised:"N", date_of_birth:"1988-12-18", nationality:"Grenadian", teacher_type:"Part Time", subjects:"Home Economics", area_of_specialisation:"Creative Arts", total_periods:"16" },
  { institution:"T.A. Marryshow Community College", territory:"Grenada", surname:"La Grenade", first_name:"Bernard", sex:"M", classification:"TT", highest_qualification:"Bachelors", years_experience:"13", cpd_hours:"24", left_service:"N", appraised:"Y", date_of_birth:"1977-06-04", nationality:"Grenadian", teacher_type:"Full Time", subjects:"Chemistry", area_of_specialisation:"STEM", total_periods:"26" },
];

export async function POST() {
  const createdAt = new Date().toISOString();
  const result = processRows(DEMO_ROWS, "staff", { createdAt, extraAliases: [] });

  if (result.batchError) {
    return NextResponse.json(result.batchError, { status: 422 });
  }

  const records = result.accepted.map((a) => a.record);
  const mapping = result.accepted.map((a) => a.mapping);
  const rejected = result.rejected;

  await fs.mkdir(OUT_DIR, { recursive: true });
  await fs.writeFile(path.join(OUT_DIR, "staff-records.json"), JSON.stringify(records, null, 2), "utf8");
  await fs.writeFile(path.join(OUT_DIR, "staff-mapping.json"), JSON.stringify(mapping, null, 2), "utf8");
  await fs.writeFile(path.join(OUT_DIR, "staff-rejected.json"), JSON.stringify(rejected, null, 2), "utf8");

  return NextResponse.json({
    ok: true,
    total: records.length,
    rejected: rejected.length,
    territories: [...new Set(records.map((r) => r.staff?.territory).filter(Boolean))].length,
    institutions: [...new Set(records.map((r) => r.staff?.institution).filter(Boolean))].length,
  });
}
